import type { Metadata } from "next";
import { cookies } from "next/headers";
import "../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import { ThemeProvider } from "next-themes";
import AppBreadcrumb from "@/components/app-breadcrumb";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <ThemeProvider attribute="class" defaultTheme="light">
      <SidebarProvider defaultOpen={defaultOpen}>
        <AppSidebar />
        <main className="p-4">
          {/* <SidebarTrigger /> */}
          <AppBreadcrumb />
          {children}
        </main>
      </SidebarProvider>
    </ThemeProvider>
  );
}
